## GAP -> Python bridge: for every group SmallGroup(size, i) with i in
## [start..stop], export (a) a PC presentation on generators ordered along
## a composition series refining the lower central series (so that S' is
## always an exact tail, as fastfusion/pcgroup.py requires), and (b) a
## generating set of Aut(G), as JSON lines to `outfile`.
##
## Usage: gap -q -b export_batch.g <size> <start> <stop> <outfile>
##
## Elementary abelian groups (class 1, trivial derived subgroup) are
## special-cased: GAP's generic AutomorphismGroup is slow for GL(n,p) (it
## does not use the obvious linear-algebra shortcut), so for these we
## supply the standard two generators of GL(n,p) directly (a Singer-cycle-
## adjacent companion matrix and a transvection, which together generate
## GL(n,p) for every n,p -- a classical fact) instead of calling
## AutomorphismGroup at all.

LoadPackage("sglppow");

## A PCGS refining the lower central series exactly, with every relative
## order p: refine *within* each lower-central-series layer H_i/H_{i+1}
## separately (via that quotient's own composition series, lifted back by
## a preimage representative), rather than asking GAP's
## CompositionSeriesThrough for a single series spanning all of them at
## once -- the latter was found, empirically, to occasionally return a
## malformed (non-monotonic-length) series for some groups in this
## library (e.g. SmallGroup(78125,2): sizes [...,125,25,5,1,5,1], the
## trailing "5,1" a spurious repeat), while refining layer-by-layer never
## exhibited this.  By construction, the generators contributed by layers
## 2..c already generate exactly H_2 = [G,G] = S', so S' is automatically
## an exact PCGS tail, as fastfusion/pcgroup.py requires.
BuildRefinedPcgs := function(G)
    local lcs, c, gens, i, Hi, Hi1, quo, Q, csQ, j, repQ, rep, m;
    lcs := LowerCentralSeriesOfGroup(G);
    c := Length(lcs) - 1;
    gens := [];
    for i in [1..c] do
        Hi := lcs[i]; Hi1 := lcs[i+1];
        quo := NaturalHomomorphismByNormalSubgroup(Hi, Hi1);
        Q := Image(quo, Hi);
        csQ := CompositionSeries(Q);
        m := Length(csQ) - 1;
        for j in [1..m] do
            repQ := First(AsList(csQ[j]), x -> not x in csQ[j+1]);
            rep := PreImagesRepresentative(quo, repQ);
            Add(gens, rep);
        od;
    od;
    return gens;
end;

PrintJSONIntList := function(stream, l)
    PrintTo(stream, "[", JoinStringsWithSeparator(List(l, String), ","), "]");
end;

ExportOne := function(stream, size, idx)
    local G, p, n, k, gens, i, pcgs, power_words, comm_words,
          j, pw, is_elab, A, autgens, images, phi, img, first, comp,
          poly, i2, trans;

    G := SmallGroup(size, idx);
    p := Factors(size)[1];
    n := Length(Factors(size));
    gens := BuildRefinedPcgs(G);
    k := Length(gens);
    pcgs := PcgsByPcSequence(FamilyObj(One(G)), gens);

    power_words := List(gens, g -> ExponentsOfPcElement(pcgs, g^p));
    comm_words := [];
    for i in [1..k-1] do
        for j in [i+1..k] do
            pw := ExponentsOfPcElement(pcgs, Comm(gens[i], gens[j]));
            if pw <> 0*pw then
                Add(comm_words, [i, j, pw]);
            fi;
        od;
    od;

    is_elab := Size(DerivedSubgroup(G)) = 1 and
               ForAll(gens, g -> ExponentsOfPcElement(pcgs, g^p) = 0*power_words[1]);

    if is_elab then
        # G is elementary abelian of rank k = n: supply the two standard
        # GL(n,p) generators (a companion matrix of a primitive polynomial,
        # realising a Singer cycle, and a transvection) directly as images
        # on the pcgs, instead of calling GAP's (slow, here) generic
        # AutomorphismGroup -- a classical fact that these two generate
        # the whole of GL(n,p) for every n >= 1, p prime.
        images := [];
        if k = 1 then
            # GL(1,p) = C_{p-1}, generated by any primitive root.
            first := [[PrimitiveRootMod(p)]];
        else
            # companion matrix of a primitive (Conway) polynomial realises
            # a Singer cycle (order p^k - 1); together with a transvection
            # this generates all of GL(k,p) (classical fact).
            poly := ConwayPolynomial(p, k);
            comp := CompanionMat(poly);
            trans := IdentityMat(k, GF(p));
            trans[1][2] := One(GF(p));
            first := [comp, trans];
        fi;
        for comp in first do
            img := [];
            for i2 in [1..k] do
                img[i2] := List(comp[i2], x -> IntFFE(x));
            od;
            Add(images, img);
        od;
    else
        A := AutomorphismGroup(G);
        autgens := GeneratorsOfGroup(A);
        images := List(autgens, phi -> List(gens, g -> ExponentsOfPcElement(pcgs, Image(phi, g))));
    fi;

    PrintTo(stream, "{\"size\":", size, ",\"index\":", idx, ",\"n\":", k, ",\"p\":", p);
    PrintTo(stream, ",\"power_words\":[");
    for i in [1..k] do
        if i > 1 then PrintTo(stream, ","); fi;
        PrintJSONIntList(stream, power_words[i]);
    od;
    PrintTo(stream, "],\"comm_words\":[");
    for i in [1..Length(comm_words)] do
        if i > 1 then PrintTo(stream, ","); fi;
        PrintTo(stream, "[", comm_words[i][1], ",", comm_words[i][2], ",");
        PrintJSONIntList(stream, comm_words[i][3]);
        PrintTo(stream, "]");
    od;
    PrintTo(stream, "],\"aut_gens\":[");
    for i in [1..Length(images)] do
        if i > 1 then PrintTo(stream, ","); fi;
        PrintTo(stream, "[");
        for j in [1..Length(images[i])] do
            if j > 1 then PrintTo(stream, ","); fi;
            PrintJSONIntList(stream, images[i][j]);
        od;
        PrintTo(stream, "]");
    od;
    PrintTo(stream, "]}\n");
end;

RunExportBatch := function(size, start, stop, outfile)
    local stream, idx;
    stream := OutputTextFile(outfile, false);
    SetPrintFormattingStatus(stream, false);
    for idx in [start..stop] do
        ExportOne(stream, size, idx);
    od;
    CloseStream(stream);
end;
