## A from-scratch implementation (not a transliteration of FusionSystems.m,
## though it computes the same mathematical object) of "the fusion system
## generated by Alperin-Goldschmidt data" and a direct, from-definition
## check of Broto-Levi-Oliver saturation. Built for correctness first,
## validated against actual finite groups (whose p-local fusion systems are
## saturated by a classical theorem, giving free ground truth with no need
## for FusionSystems.m/MAGMA) before any attempt to make it scale to 5^7.
##
## A FUSION DATUM is built by FusionDatum(Sgrp, AutFSgens, essentialsData):
##   Sgrp          -- the p-group (a GAP group)
##   AutFSgens     -- generators (as automorphisms of Sgrp) for Aut_F(S)
##                     (Inn(S) is added automatically).
##   essentialsData -- list of records { grp := <subgroup of Sgrp>,
##                     autFgens := <automorphisms of grp generating
##                     Aut_F(grp)> }.
## Internally this builds B = Sgrp . <AutFSgens, Inn(Sgrp)> via
## SemidirectProduct, with S realized as the normal image of Sgrp in B, and
## transports the essentials' data into B's frame, so everything from here
## on (Normalizer, Centralizer, AllSubgroups, conjugation) happens inside
## the single ambient permutation group B -- conjugation by elements of B
## stands in for "automorphisms of S coming from Aut_F(S)".
##
## THE FUSION GRAPH's nodes are B-conjugacy classes of ALL subgroups of S
## (not just S-centric ones: non-centric overgroups are needed as
## bookkeeping intermediates when checking the extension axiom, even though
## the axioms themselves are only asserted at F-centric subgroups).

## A Hall p'-subgroup of G (the complementary-primes Hall subgroup to p).
HallPPrimeSubgroup := function(G, p)
    local primes;
    primes := Difference(PrimeDivisors(Size(G)), [p]);
    return HallSubgroup(G, primes);
end;

## Action function for Orbit/RepresentativeAction/Stabilizer when the
## "group" consists of automorphism mappings (GroupHomomorphismByImagesNC
## objects) acting on subgroups, as opposed to literal group elements
## acting by conjugation (for which OnPoints / `^` already works).
OnSubgroupsByHom := function(H, g)
    return Image(g, H);
end;

TransportAutomorphism := function(emb, dom, domImg, aut)
    local gens, imgs;
    gens := GeneratorsOfGroup(domImg);
    imgs := List(gens, g -> Image(emb, Image(aut, PreImagesRepresentative(emb, g))));
    return GroupHomomorphismByImagesNC(domImg, domImg, gens, imgs);
end;

FusionDatum := function(Sgrp, AutFSgens, essentialsData)
    local innGens, allAutFSgens, AutFS, B, embS, embA, Simg, essImg, ed,
          grpImg, autFgensImg, autFImg, datum;

    innGens := List(GeneratorsOfGroup(Sgrp), s -> ConjugatorAutomorphism(Sgrp, s));
    allAutFSgens := Concatenation(AutFSgens, innGens);
    AutFS := Group(allAutFSgens);
    if Size(AutFS) = 1 then
        AutFS := Group(innGens);
    fi;

    B := SemidirectProduct(AutFS, Sgrp);
    embA := Embedding(B, 1);
    embS := Embedding(B, 2);
    Simg := Image(embS, Sgrp);

    essImg := [];
    for ed in essentialsData do
        grpImg := Image(embS, ed.grp);
        autFgensImg := List(ed.autFgens,
            a -> TransportAutomorphism(embS, ed.grp, grpImg, a));
        autFImg := Group(autFgensImg);
        Add(essImg, rec(grp := grpImg, autF := autFImg));
    od;

    datum := rec(S := Simg, B := B, essentials := essImg, p := PrimePGroup(Simg));
    return datum;
end;

AllCentricSubgroups := function(S)
    return Filtered(AllSubgroups(S), P -> Centralizer(S, P) = Centre(P));
end;

BConjugacyClasses := function(B, subs)
    local classes, seen, Pgrp, cls, Qgrp, found;
    classes := []; seen := [];
    for Pgrp in subs do
        if Pgrp in seen then continue; fi;
        cls := rec(rep := Pgrp, members := [rec(grp := Pgrp, b := One(B))]);
        Add(seen, Pgrp);
        for Qgrp in subs do
            if Qgrp in seen or Size(Qgrp) <> Size(Pgrp) then continue; fi;
            found := RepresentativeAction(B, Pgrp, Qgrp, OnPoints);
            if found <> fail then
                Add(cls.members, rec(grp := Qgrp, b := found));
                Add(seen, Qgrp);
            fi;
        od;
        Add(classes, cls);
    od;
    return classes;
end;

## Build the fusion graph on B-classes of ALL subgroups of S. Edges come
## from each essential's autF identifying subgroups of (B-conjugates of)
## that essential which lie in different B-classes.
BuildFusionGraph := function(datum)
    local S, B, classes, classOfCache, classOf, adjacency, ess, essGrp,
          autF, subsOfEss, seen, Qgrp, orbit, i, j, Pgrp, Rgrp, cIdx, k,
          found, map1, map2, allSubs;

    S := datum.S; B := datum.B;
    allSubs := AllSubgroups(S);
    classes := BConjugacyClasses(B, allSubs);

    classOfCache := NewDictionary(fail, true);
    classOf := function(Pgrp)
        local cached, i, m;
        cached := LookupDictionary(classOfCache, Pgrp);
        if cached <> fail then return cached; fi;
        for i in [1 .. Length(classes)] do
            for m in classes[i].members do
                if m.grp = Pgrp then
                    AddDictionary(classOfCache, Pgrp, i);
                    return i;
                fi;
            od;
        od;
        return fail;
    end;

    adjacency := List(classes, c -> []);

    for ess in datum.essentials do
        essGrp := ess.grp; autF := ess.autF;
        subsOfEss := Filtered(allSubs, Qgrp -> IsSubset(essGrp, Qgrp));
        seen := [];
        for Qgrp in subsOfEss do
            if Qgrp in seen then continue; fi;
            orbit := Orbit(autF, Qgrp, OnSubgroupsByHom);
            orbit := Filtered(orbit, x -> x in subsOfEss);
            UniteSet(seen, orbit);
            for i in [1 .. Length(orbit)] do
                for j in [i+1 .. Length(orbit)] do
                    Pgrp := orbit[i]; Rgrp := orbit[j];
                    cIdx := classOf(Pgrp); k := classOf(Rgrp);
                    if cIdx = fail or k = fail or cIdx = k then continue; fi;
                    if ForAny(adjacency[cIdx], a -> a.j = k) then continue; fi;
                    found := RepresentativeAction(autF, Pgrp, Rgrp, OnSubgroupsByHom);
                    if found = fail then continue; fi;
                    map1 := GroupHomomorphismByFunction(Pgrp, Rgrp, x -> Image(found, x));
                    map2 := GroupHomomorphismByFunction(Rgrp, Pgrp, x -> PreImage(found, x));
                    Add(adjacency[cIdx], rec(j := k, map := map1));
                    Add(adjacency[k], rec(j := cIdx, map := map2));
                od;
            od;
        od;
    od;

    return rec(S := S, B := B, p := datum.p, classes := classes,
               classOf := classOf, adjacency := adjacency);
end;

FusionComponents := function(fg)
    local n, seen, comps, i, comp, queue, j, a;
    n := Length(fg.classes);
    seen := List([1..n], x -> false);
    comps := [];
    for i in [1..n] do
        if seen[i] then continue; fi;
        comp := [i]; seen[i] := true; queue := [i];
        while Length(queue) > 0 do
            j := Remove(queue);
            for a in fg.adjacency[j] do
                if not seen[a.j] then
                    seen[a.j] := true; Add(comp, a.j); Add(queue, a.j);
                fi;
            od;
        od;
        Add(comps, comp);
    od;
    return comps;
end;

FusionComponentOf := function(fg, comps, i)
    return First(comps, c -> i in c);
end;

FusionPath := function(fg, i, j)
    local n, prevEdge, seen, queue, cur, a, path, k;
    if i = j then return []; fi;
    n := Length(fg.classes);
    prevEdge := List([1..n], x -> fail);
    seen := List([1..n], x -> false);
    seen[i] := true; queue := [i];
    while Length(queue) > 0 do
        cur := Remove(queue, 1);
        for a in fg.adjacency[cur] do
            if not seen[a.j] then
                seen[a.j] := true; prevEdge[a.j] := rec(from := cur, edge := a);
                Add(queue, a.j);
            fi;
        od;
    od;
    if not seen[j] then return fail; fi;
    path := []; k := j;
    while k <> i do
        Add(path, prevEdge[k].edge, 1);
        k := prevEdge[k].from;
    od;
    return path;
end;

## Is Pgrp F-conjugate to Qgrp? Returns [true, map] (map: Pgrp -> Qgrp an
## explicit F-isomorphism) or [false, fail].
FIsConjugate := function(fg, Pgrp, Qgrp)
    local iP, iQ, path, mP, mQ, bP, bQ, totalMap, edge;
    if Size(Pgrp) <> Size(Qgrp) then return [false, fail]; fi;
    iP := fg.classOf(Pgrp); iQ := fg.classOf(Qgrp);
    if iP = fail or iQ = fail then return [false, fail]; fi;
    path := FusionPath(fg, iP, iQ);
    if path = fail then return [false, fail]; fi;
    mP := First(fg.classes[iP].members, x -> x.grp = Pgrp);
    mQ := First(fg.classes[iQ].members, x -> x.grp = Qgrp);
    bP := mP.b; bQ := mQ.b;
    totalMap := GroupHomomorphismByFunction(Pgrp, fg.classes[iP].rep, x -> x^(bP^-1));
    for edge in path do
        totalMap := CompositionMapping(edge.map, totalMap);
    od;
    totalMap := CompositionMapping(
        GroupHomomorphismByFunction(fg.classes[iQ].rep, Qgrp, x -> x^bQ),
        totalMap);
    return [true, totalMap];
end;

FIsCentric := function(fg, comps, Pgrp)
    local iP, comp, idx, Qgrp;
    iP := fg.classOf(Pgrp);
    if iP = fail then return fail; fi;
    comp := FusionComponentOf(fg, comps, iP);
    for idx in comp do
        for Qgrp in List(fg.classes[idx].members, m -> m.grp) do
            if Centralizer(fg.S, Qgrp) <> Centre(Qgrp) then return false; fi;
        od;
    od;
    return true;
end;

FIsFullyNormalized := function(fg, comps, Pgrp)
    local iP, comp, idx, best, Qgrp;
    iP := fg.classOf(Pgrp);
    comp := FusionComponentOf(fg, comps, iP);
    best := Size(Normalizer(fg.S, Pgrp));
    for idx in comp do
        for Qgrp in List(fg.classes[idx].members, m -> m.grp) do
            if Size(Normalizer(fg.S, Qgrp)) > best then return false; fi;
        od;
    od;
    return true;
end;

FIsFullyCentralized := function(fg, comps, Pgrp)
    local iP, comp, idx, best, Qgrp;
    iP := fg.classOf(Pgrp);
    comp := FusionComponentOf(fg, comps, iP);
    best := Size(Centralizer(fg.S, Pgrp));
    for idx in comp do
        for Qgrp in List(fg.classes[idx].members, m -> m.grp) do
            if Size(Centralizer(fg.S, Qgrp)) > best then return false; fi;
        od;
    od;
    return true;
end;

## Aut_F(Pgrp), generated by B-conjugation on Pgrp together with, for every
## other subgroup Qgrp F-conjugate to Pgrp, "go to Qgrp, apply
## B-conjugation there, come back" -- the closure defining the generated
## fusion system, correct by construction.
FAutomorphismGroup := function(fg, comps, Pgrp)
    local B, NBP, gens, iP, comp, idx, Qgrp, conj, NBQ, g, roundTrip, autGens;
    B := fg.B;
    NBP := Stabilizer(B, Pgrp, OnPoints);
    gens := List(GeneratorsOfGroup(NBP), b -> ConjugatorAutomorphism(Pgrp, b));
    iP := fg.classOf(Pgrp);
    comp := FusionComponentOf(fg, comps, iP);
    for idx in comp do
        for Qgrp in List(fg.classes[idx].members, m -> m.grp) do
            if Size(Qgrp) <> Size(Pgrp) or Qgrp = Pgrp then continue; fi;
            conj := FIsConjugate(fg, Pgrp, Qgrp);
            if conj[1] = false then continue; fi;
            NBQ := Stabilizer(B, Qgrp, OnPoints);
            for g in GeneratorsOfGroup(NBQ) do
                roundTrip := CompositionMapping(InverseGeneralMapping(conj[2]),
                                 CompositionMapping(ConjugatorAutomorphism(Qgrp, g), conj[2]));
                Add(gens, roundTrip);
            od;
        od;
    od;
    if Length(GeneratorsOfGroup(Pgrp)) = 0 then
        return Group(IdentityMapping(Pgrp));
    fi;
    autGens := List(gens, g -> GroupHomomorphismByImagesNC(Pgrp, Pgrp,
                     GeneratorsOfGroup(Pgrp), List(GeneratorsOfGroup(Pgrp), x -> Image(g, x))));
    return Group(autGens);
end;

## Aut_V(Pgrp) as an explicit subgroup of Aut(Pgrp) (automorphisms of Pgrp
## induced by conjugation from elements of Vgrp, Pgrp normal in Vgrp).
LocalAutomizer := function(Vgrp, Pgrp)
    local gens;
    gens := List(GeneratorsOfGroup(Vgrp), v -> GroupHomomorphismByImagesNC(
        Pgrp, Pgrp, GeneratorsOfGroup(Pgrp), List(GeneratorsOfGroup(Pgrp), x -> x^v)));
    return Group(gens);
end;

FIsFullyAutomised := function(fg, comps, Pgrp)
    local autFP, autSP, p;
    autFP := FAutomorphismGroup(fg, comps, Pgrp);
    autSP := LocalAutomizer(Normalizer(fg.S, Pgrp), Pgrp);
    p := fg.p;
    return Size(autSP) = p ^ PValuation(Size(autFP), p);
end;

## The extension/receptivity axiom at Pgrp, in its standard operational form
## (see e.g. FusionSystems.m's SurjectivityProperty, whose mathematical
## content -- not its MAGMA-specific bookkeeping -- this follows): for every
## overgroup Vgrp with Pgrp <= Vgrp <= N_S(Pgrp), Vgrp/Pgrp nontrivial, the
## automorphisms of Pgrp that EXTEND to Vgrp (obtained by restricting
## elements of Aut_F(Vgrp) that stabilise Pgrp) must equal exactly those
## automorphisms of Pgrp, within Aut_F(Pgrp), that normalise Aut_Vgrp(Pgrp).
FReceptive := function(fg, comps, Pgrp)
    local nsp, autFP, quotient, nat, subsOfQuotient, sq, Vgrp, autFV,
          localAutV, normAutFP, restrictedGens, restrictedAuts, restricted,
          g, img;
    nsp := Normalizer(fg.S, Pgrp);
    if Size(nsp) = Size(Pgrp) then return true; fi; ## no proper overgroups
    autFP := FAutomorphismGroup(fg, comps, Pgrp);
    nat := NaturalHomomorphismByNormalSubgroup(nsp, Pgrp);
    quotient := Range(nat);
    subsOfQuotient := Filtered(AllSubgroups(quotient), q -> Size(q) > 1);
    for sq in subsOfQuotient do
        Vgrp := PreImage(nat, sq);
        autFV := FAutomorphismGroup(fg, comps, Vgrp);
        localAutV := LocalAutomizer(Vgrp, Pgrp);
        normAutFP := Normalizer(autFP, localAutV);
        ## {automorphisms of Pgrp extending to Vgrp} = restrict, to Pgrp, the
        ## stabiliser (within Aut_F(Vgrp)) of Pgrp as a subgroup of Vgrp.
        restrictedGens := [];
        for g in GeneratorsOfGroup(autFV) do
            if Image(g, Pgrp) = Pgrp then
                Add(restrictedGens, GroupHomomorphismByImagesNC(Pgrp, Pgrp,
                    GeneratorsOfGroup(Pgrp), List(GeneratorsOfGroup(Pgrp), x -> Image(g, x))));
            fi;
        od;
        ## elements of autFV stabilising Pgrp setwise may not be generators;
        ## take the full stabiliser in autFV of Pgrp (as a set), not just
        ## generators that happen to.
        restricted := Stabilizer(autFV, Pgrp, OnSubgroupsByHom);
        restrictedAuts := List(GeneratorsOfGroup(restricted), g ->
            GroupHomomorphismByImagesNC(Pgrp, Pgrp, GeneratorsOfGroup(Pgrp),
                List(GeneratorsOfGroup(Pgrp), x -> Image(g, x))));
        restrictedAuts := Group(restrictedAuts);
        if restrictedAuts <> normAutFP then
            return false;
        fi;
    od;
    return true;
end;

## Direct, from-definition saturation check: for every F-class (connected
## component) of subgroups, require that some member Pgrp with Size > 1 is
## simultaneously F-centric, fully automised and receptive (the standard
## equivalent reformulation of the Sylow + extension axioms, see e.g.
## Linckelmann's lecture notes Prop. 2.5 or Broto-Levi-Oliver themselves).
IsSaturatedDatum := function(datum)
    local fg, comps, comp, Pgrp, isCentric, foundGood, idx, m;
    fg := BuildFusionGraph(datum);
    comps := FusionComponents(fg);
    for comp in comps do
        if Size(fg.classes[comp[1]].rep) = 1 then continue; fi; ## trivial subgroup
        ## S itself is always F-centric (C_S(S)=Z(S)) and always its own
        ## F-class (no proper F-conjugates), so it goes through exactly the
        ## same fully-automised + receptive check as everything else below
        ## -- this is precisely where O^p(F)=F / Aut_F(S)/Inn(S) being a
        ## p'-group gets enforced (Aut_S(S)=Inn(S) must be Sylow-p in
        ## Aut_F(S)), so it must not be skipped.

        ## F-centric is a property of the whole F-class (every F-conjugate
        ## must satisfy C_S(.) = Z(.)): if any member fails it, none of
        ## them can be F-centric, and the axioms simply don't apply to this
        ## class -- that is not a saturation failure, just nothing to check.
        isCentric := true;
        for idx in comp do
            for m in fg.classes[idx].members do
                if Centralizer(fg.S, m.grp) <> Centre(m.grp) then
                    isCentric := false; break;
                fi;
            od;
            if not isCentric then break; fi;
        od;
        if not isCentric then continue; fi;

        foundGood := false;
        for idx in comp do
            for m in fg.classes[idx].members do
                Pgrp := m.grp;
                if FIsFullyAutomised(fg, comps, Pgrp) and FReceptive(fg, comps, Pgrp) then
                    foundGood := true; break;
                fi;
            od;
            if foundGood then break; fi;
        od;
        if not foundGood then return false; fi;
    od;
    return true;
end;
